Transform: AWS::Serverless-2016-10-31

Resources:
  travels:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub ${App}-${Env}-${Name}-travels
      AttributeDefinitions:
        - AttributeName: Country
          AttributeType: "S"
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: Country
          KeyType: HASH

  samtable:
    Type: AWS::Serverless::SimpleTable